db:
  configurations:
    0:
      url: jdbc:mysql://local:3306/1?useSSL=false&serverTimezone=CET
      username:
      driver: com.mysql.cj.jdbc.Driver
      password:
    1:
      url: jdbc:mysql://local:3306/2?useSSL=false&serverTimezone=CET
      username:
      driver: com.mysql.cj.jdbc.Driver
      password:
server:
  port: 8080